import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const hoursFromNow = (hours: number) =>
  new Date(Date.now() + hours * 60 * 60 * 1000);

async function main() {
  await prisma.eventLog.deleteMany();
  await prisma.container.deleteMany();
  await prisma.ship.deleteMany();
  await prisma.carrier.deleteMany();

  const [atlas, vectra, transmar, sulport] = await Promise.all([
    prisma.carrier.create({
      data: {
        name: 'Atlas Cargo Road',
        cnpj: '12.345.678/0001-90',
        driverName: 'Marcos Diniz',
        truckPlate: 'ABC1D23',
        phone: '+55 11 97123-4455',
        email: 'operacoes@atlascargo.com.br',
        status: 'EM_OPERACAO',
      },
    }),
    prisma.carrier.create({
      data: {
        name: 'Vectra Logistica Integrada',
        cnpj: '23.456.789/0001-10',
        driverName: 'Daniela Costa',
        truckPlate: 'BRA8F71',
        phone: '+55 13 98115-9001',
        email: 'dispatch@vectralog.com.br',
        status: 'EM_OPERACAO',
      },
    }),
    prisma.carrier.create({
      data: {
        name: 'TransMar Operacoes',
        cnpj: '34.567.890/0001-20',
        driverName: 'Henrique Alves',
        truckPlate: 'QWE4R67',
        phone: '+55 13 98890-1122',
        email: 'yard@transmar.com.br',
        status: 'DISPONIVEL',
      },
    }),
    prisma.carrier.create({
      data: {
        name: 'SulPort Haulage',
        cnpj: '45.678.901/0001-30',
        driverName: 'Patricia Gomes',
        truckPlate: 'SPO7K91',
        phone: '+55 11 96444-2211',
        email: 'fleet@sulport.com.br',
        status: 'DISPONIVEL',
      },
    }),
  ]);

  const [aurora, blueEstuary, atlanticForge, pacificHorizon] =
    await Promise.all([
      prisma.ship.create({
        data: {
          name: 'MV Aurora Meridian',
          company: 'Maersk Line',
          eta: hoursFromNow(18),
          etd: hoursFromNow(42),
          origin: 'Shanghai, CN',
          destination: 'Santos, BR',
          status: 'PREVISTO',
          expectedContainers: 18,
        },
      }),
      prisma.ship.create({
        data: {
          name: 'MV Blue Estuary',
          company: 'CMA CGM',
          eta: hoursFromNow(-30),
          etd: hoursFromNow(18),
          actualArrivalAt: hoursFromNow(-28),
          origin: 'Busan, KR',
          destination: 'Santos, BR',
          status: 'ATRACADO',
          expectedContainers: 24,
        },
      }),
      prisma.ship.create({
        data: {
          name: 'MV Atlantic Forge',
          company: 'Hapag-Lloyd',
          eta: hoursFromNow(-180),
          etd: hoursFromNow(-96),
          actualArrivalAt: hoursFromNow(-176),
          origin: 'Antwerp, BE',
          destination: 'Santos, BR',
          status: 'PARTIU',
          expectedContainers: 20,
        },
      }),
      prisma.ship.create({
        data: {
          name: 'MV Pacific Horizon',
          company: 'ONE',
          eta: hoursFromNow(-22),
          etd: hoursFromNow(30),
          origin: 'Singapore, SG',
          destination: 'Santos, BR',
          status: 'ATRASADO',
          expectedContainers: 16,
        },
      }),
    ]);

  const containers = await Promise.all([
    prisma.container.create({
      data: {
        containerCode: 'MSKU5274910',
        type: 'FT40',
        weight: 24100,
        cargoDescription: 'Bobinas de aco galvanizado',
        clientName: 'Vale Industrial',
        origin: 'Shanghai, CN',
        destination: 'Cubatao, BR',
        status: 'AGUARDANDO_NAVIO',
        shipId: aurora.id,
        carrierId: atlas.id,
        eta: hoursFromNow(18),
        bookingDate: hoursFromNow(-240),
        sealNumber: 'SL934820',
        notes: 'Janela de descarga prioritaria para manutencao industrial.',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'CMAU1948203',
        type: 'FT20',
        weight: 12800,
        cargoDescription: 'Componentes eletricos para automacao',
        clientName: 'MetalNova',
        origin: 'Ningbo, CN',
        destination: 'Guarulhos, BR',
        status: 'AGUARDANDO_NAVIO',
        shipId: aurora.id,
        carrierId: vectra.id,
        eta: hoursFromNow(18),
        bookingDate: hoursFromNow(-216),
        sealNumber: 'EL552090',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'TGBU8812742',
        type: 'FT40',
        weight: 22450,
        cargoDescription: 'Tubulacoes industriais',
        clientName: 'BioSteel',
        origin: 'Busan, KR',
        destination: 'Campinas, BR',
        status: 'NO_PORTO',
        shipId: blueEstuary.id,
        carrierId: transmar.id,
        eta: hoursFromNow(-30),
        bookingDate: hoursFromNow(-264),
        portEntryAt: hoursFromNow(-26),
        unloadedAt: hoursFromNow(-25),
        sealNumber: 'BS102990',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'MEDU4427811',
        type: 'FT20',
        weight: 11960,
        cargoDescription: 'Painel solar e inversores',
        clientName: 'BioSteel',
        origin: 'Busan, KR',
        destination: 'Sorocaba, BR',
        status: 'EM_FISCALIZACAO',
        shipId: blueEstuary.id,
        carrierId: sulport.id,
        eta: hoursFromNow(-30),
        bookingDate: hoursFromNow(-250),
        portEntryAt: hoursFromNow(-24),
        unloadedAt: hoursFromNow(-23),
        inspectionStartedAt: hoursFromNow(-16),
        sealNumber: 'EC778210',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'HLCU7758209',
        type: 'FT40',
        weight: 21120,
        cargoDescription: 'Ingredientes alimenticios refrigerados',
        clientName: 'Quanta Foods',
        origin: 'Busan, KR',
        destination: 'Jundiai, BR',
        status: 'LIBERADO',
        shipId: blueEstuary.id,
        carrierId: sulport.id,
        eta: hoursFromNow(-30),
        bookingDate: hoursFromNow(-240),
        portEntryAt: hoursFromNow(-22),
        unloadedAt: hoursFromNow(-21),
        inspectionStartedAt: hoursFromNow(-14),
        customsReleasedAt: hoursFromNow(-8),
        sealNumber: 'QD663210',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'OOLU6439102',
        type: 'FT20',
        weight: 13750,
        cargoDescription: 'Maquinas de usinagem CNC',
        clientName: 'Nexa Components',
        origin: 'Antwerp, BE',
        destination: 'Caxias do Sul, BR',
        status: 'EM_TRANSPORTE',
        shipId: atlanticForge.id,
        carrierId: atlas.id,
        eta: hoursFromNow(-180),
        bookingDate: hoursFromNow(-360),
        portEntryAt: hoursFromNow(-150),
        unloadedAt: hoursFromNow(-148),
        inspectionStartedAt: hoursFromNow(-140),
        customsReleasedAt: hoursFromNow(-128),
        transportStartedAt: hoursFromNow(-36),
        sealNumber: 'NC120045',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'TRHU5550198',
        type: 'FT40',
        weight: 19800,
        cargoDescription: 'Resinas especiais para industria quimica',
        clientName: 'LogiChem',
        origin: 'Antwerp, BE',
        destination: 'Paulinia, BR',
        status: 'EM_TRANSPORTE',
        shipId: atlanticForge.id,
        carrierId: vectra.id,
        eta: hoursFromNow(-180),
        bookingDate: hoursFromNow(-348),
        portEntryAt: hoursFromNow(-144),
        unloadedAt: hoursFromNow(-142),
        inspectionStartedAt: hoursFromNow(-132),
        customsReleasedAt: hoursFromNow(-118),
        transportStartedAt: hoursFromNow(-24),
        sealNumber: 'LC892001',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'FSCU2201945',
        type: 'FT20',
        weight: 10350,
        cargoDescription: 'Ferramentas de corte e abrasivos',
        clientName: 'Vale Industrial',
        origin: 'Antwerp, BE',
        destination: 'Piracicaba, BR',
        status: 'ENTREGUE',
        shipId: atlanticForge.id,
        carrierId: atlas.id,
        eta: hoursFromNow(-180),
        bookingDate: hoursFromNow(-420),
        portEntryAt: hoursFromNow(-170),
        unloadedAt: hoursFromNow(-168),
        inspectionStartedAt: hoursFromNow(-160),
        customsReleasedAt: hoursFromNow(-150),
        transportStartedAt: hoursFromNow(-120),
        deliveredAt: hoursFromNow(-70),
        sealNumber: 'VI401100',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'CAIU7701820',
        type: 'FT40',
        weight: 22640,
        cargoDescription: 'Proteina vegetal ensacada',
        clientName: 'Quanta Foods',
        origin: 'Antwerp, BE',
        destination: 'Ribeirao Preto, BR',
        status: 'ENTREGUE',
        shipId: atlanticForge.id,
        carrierId: sulport.id,
        eta: hoursFromNow(-180),
        bookingDate: hoursFromNow(-390),
        portEntryAt: hoursFromNow(-165),
        unloadedAt: hoursFromNow(-163),
        inspectionStartedAt: hoursFromNow(-152),
        customsReleasedAt: hoursFromNow(-144),
        transportStartedAt: hoursFromNow(-110),
        deliveredAt: hoursFromNow(-48),
        sealNumber: 'QF004811',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'TEMU1294876',
        type: 'FT20',
        weight: 11870,
        cargoDescription: 'Bombas hidraulicas industriais',
        clientName: 'Nexa Components',
        origin: 'Singapore, SG',
        destination: 'Joinville, BR',
        status: 'ATRASADO',
        shipId: pacificHorizon.id,
        carrierId: transmar.id,
        eta: hoursFromNow(-22),
        bookingDate: hoursFromNow(-300),
        sealNumber: 'NH778320',
        notes: 'Atraso causado por congestionamento no corredor maritimo.',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'WHLU3901274',
        type: 'FT40',
        weight: 21560,
        cargoDescription: 'Fertilizantes especiais a granel',
        clientName: 'AgroVista',
        origin: 'Busan, KR',
        destination: 'Uberlandia, BR',
        status: 'NO_PORTO',
        shipId: blueEstuary.id,
        carrierId: transmar.id,
        eta: hoursFromNow(-30),
        bookingDate: hoursFromNow(-275),
        portEntryAt: hoursFromNow(-20),
        unloadedAt: hoursFromNow(-19),
        sealNumber: 'AG300145',
      },
    }),
    prisma.container.create({
      data: {
        containerCode: 'MSCU7784412',
        type: 'FT20',
        weight: 10920,
        cargoDescription: 'Equipamentos de laboratorio',
        clientName: 'TechMills',
        origin: 'Busan, KR',
        destination: 'Barueri, BR',
        status: 'LIBERADO',
        shipId: blueEstuary.id,
        carrierId: sulport.id,
        eta: hoursFromNow(-30),
        bookingDate: hoursFromNow(-260),
        portEntryAt: hoursFromNow(-18),
        unloadedAt: hoursFromNow(-17),
        inspectionStartedAt: hoursFromNow(-12),
        customsReleasedAt: hoursFromNow(-6),
        sealNumber: 'TM991210',
      },
    }),
  ]);

  const byCode = Object.fromEntries(
    containers.map((container) => [container.containerCode, container]),
  );

  await prisma.eventLog.createMany({
    data: [
      {
        containerId: byCode.MSKU5274910.id,
        type: 'NAVIO_PREVISTO',
        title: 'Janela de atracacao confirmada',
        description: 'O navio foi programado para chegada ao porto de Santos.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-220),
      },
      {
        containerId: byCode.CMAU1948203.id,
        type: 'NAVIO_PREVISTO',
        title: 'Carga confirmada no booking',
        description: 'Reserva validada para embarque com prioridade de descarga.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-210),
      },
      {
        containerId: byCode.TGBU8812742.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Carga vinculada ao navio MV Blue Estuary.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-240),
      },
      {
        containerId: byCode.TGBU8812742.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'MV Blue Estuary atracou e iniciou a descarga.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-28),
      },
      {
        containerId: byCode.TGBU8812742.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Contêiner posicionado no patio alfandegado.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-25),
      },
      {
        containerId: byCode.MEDU4427811.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Carga vinculada ao navio MV Blue Estuary.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-238),
      },
      {
        containerId: byCode.MEDU4427811.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'MV Blue Estuary atracou e iniciou a descarga.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-28),
      },
      {
        containerId: byCode.MEDU4427811.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Contêiner posicionado para inspeção documental.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-23),
      },
      {
        containerId: byCode.MEDU4427811.id,
        type: 'EM_FISCALIZACAO',
        title: 'Fiscalizacao em andamento',
        description: 'Receita iniciou conferencia fisica da carga.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-16),
      },
      {
        containerId: byCode.HLCU7758209.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Carga associada a escala de importacao refrigerada.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-235),
      },
      {
        containerId: byCode.HLCU7758209.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'Descarga iniciada com priorizacao de pereciveis.',
        location: 'Cais refrigerado',
        occurredAt: hoursFromNow(-28),
      },
      {
        containerId: byCode.HLCU7758209.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Contêiner direcionado para zona de inspeção.',
        location: 'Patio refrigerado',
        occurredAt: hoursFromNow(-21),
      },
      {
        containerId: byCode.HLCU7758209.id,
        type: 'EM_FISCALIZACAO',
        title: 'Fiscalizacao em andamento',
        description: 'Documentacao e temperatura auditadas pela aduana.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-14),
      },
      {
        containerId: byCode.HLCU7758209.id,
        type: 'LIBERADO',
        title: 'Carga liberada',
        description: 'Carga pronta para agendamento de transporte rodoviario.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-8),
      },
      {
        containerId: byCode.OOLU6439102.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Container reservado para importacao de maquinario.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-340),
      },
      {
        containerId: byCode.OOLU6439102.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'MV Atlantic Forge finalizou atracacao no terminal.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-176),
      },
      {
        containerId: byCode.OOLU6439102.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Carga descarregada e enviada para patio de armazenagem.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-148),
      },
      {
        containerId: byCode.OOLU6439102.id,
        type: 'EM_FISCALIZACAO',
        title: 'Fiscalizacao em andamento',
        description: 'Equipe aduaneira conferiu serial dos equipamentos.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-140),
      },
      {
        containerId: byCode.OOLU6439102.id,
        type: 'LIBERADO',
        title: 'Carga liberada',
        description: 'Documentacao final aprovada para retirada do porto.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-128),
      },
      {
        containerId: byCode.OOLU6439102.id,
        type: 'SAIU_PARA_TRANSPORTE',
        title: 'Saida para transporte',
        description: 'Caminhao liberado no gate out rumo ao cliente.',
        location: 'Gate out do terminal',
        occurredAt: hoursFromNow(-36),
      },
      {
        containerId: byCode.TRHU5550198.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Carga vinculada a importacao de insumos quimicos.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-330),
      },
      {
        containerId: byCode.TRHU5550198.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'MV Atlantic Forge atracou dentro da janela prevista.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-176),
      },
      {
        containerId: byCode.TRHU5550198.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Carga descarregada com tratativa para material controlado.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-142),
      },
      {
        containerId: byCode.TRHU5550198.id,
        type: 'EM_FISCALIZACAO',
        title: 'Fiscalizacao em andamento',
        description: 'Lacre e nota fiscal conferidos.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-132),
      },
      {
        containerId: byCode.TRHU5550198.id,
        type: 'LIBERADO',
        title: 'Carga liberada',
        description: 'Liberação concluida para remessa ao cliente final.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-118),
      },
      {
        containerId: byCode.TRHU5550198.id,
        type: 'SAIU_PARA_TRANSPORTE',
        title: 'Saida para transporte',
        description: 'Carga embarcada em carreta dedicada.',
        location: 'Gate out do terminal',
        occurredAt: hoursFromNow(-24),
      },
      {
        containerId: byCode.FSCU2201945.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Importacao confirmada para ferramentas industriais.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-400),
      },
      {
        containerId: byCode.FSCU2201945.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'Escala concluida no terminal de Santos.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-176),
      },
      {
        containerId: byCode.FSCU2201945.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Ferramentas encaminhadas para zona de inspeção.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-168),
      },
      {
        containerId: byCode.FSCU2201945.id,
        type: 'EM_FISCALIZACAO',
        title: 'Fiscalizacao em andamento',
        description: 'Carga verificada e liberada sem ressalvas.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-160),
      },
      {
        containerId: byCode.FSCU2201945.id,
        type: 'LIBERADO',
        title: 'Carga liberada',
        description: 'Retirada agendada para janela noturna.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-150),
      },
      {
        containerId: byCode.FSCU2201945.id,
        type: 'SAIU_PARA_TRANSPORTE',
        title: 'Saida para transporte',
        description: 'Unidade deixou o terminal em comboio de distribuição.',
        location: 'Gate out do terminal',
        occurredAt: hoursFromNow(-120),
      },
      {
        containerId: byCode.FSCU2201945.id,
        type: 'ENTREGUE',
        title: 'Entrega concluida',
        description: 'Carga recebida pela planta industrial com protocolo assinado.',
        location: 'Piracicaba, BR',
        occurredAt: hoursFromNow(-70),
      },
      {
        containerId: byCode.CAIU7701820.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Carga de alimentos confirmada para descarga controlada.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-380),
      },
      {
        containerId: byCode.CAIU7701820.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'Escala concluida sem desvios operacionais.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-176),
      },
      {
        containerId: byCode.CAIU7701820.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Carga alocada em patio com rastreio prioritario.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-163),
      },
      {
        containerId: byCode.CAIU7701820.id,
        type: 'EM_FISCALIZACAO',
        title: 'Fiscalizacao em andamento',
        description: 'Documentos sanitarios conferidos.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-152),
      },
      {
        containerId: byCode.CAIU7701820.id,
        type: 'LIBERADO',
        title: 'Carga liberada',
        description: 'Carga apta para expedição ao centro de distribuicao.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-144),
      },
      {
        containerId: byCode.CAIU7701820.id,
        type: 'SAIU_PARA_TRANSPORTE',
        title: 'Saida para transporte',
        description: 'Carreta saiu do porto com janela monitorada.',
        location: 'Gate out do terminal',
        occurredAt: hoursFromNow(-110),
      },
      {
        containerId: byCode.CAIU7701820.id,
        type: 'ENTREGUE',
        title: 'Entrega concluida',
        description: 'Centro de distribuicao recebeu a carga sem avarias.',
        location: 'Ribeirao Preto, BR',
        occurredAt: hoursFromNow(-48),
      },
      {
        containerId: byCode.TEMU1294876.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Booking confirmado para bombas hidraulicas.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-280),
      },
      {
        containerId: byCode.TEMU1294876.id,
        type: 'STATUS_ATUALIZADO',
        title: 'Operacao com atraso',
        description: 'A escala foi impactada por congestionamento maritimo e ficou atrasada.',
        location: 'Torre de controle',
        occurredAt: hoursFromNow(-20),
      },
      {
        containerId: byCode.WHLU3901274.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Fertilizantes planejados para descarga em lote.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-250),
      },
      {
        containerId: byCode.WHLU3901274.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'Escala confirmada e descarga liberada para o lote.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-28),
      },
      {
        containerId: byCode.WHLU3901274.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Container posicionado para montagem de rota interna.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-19),
      },
      {
        containerId: byCode.MSCU7784412.id,
        type: 'NAVIO_PREVISTO',
        title: 'Previsao de navio registrada',
        description: 'Equipamentos laboratoriais confirmados para descarga.',
        location: 'Planejamento operacional',
        occurredAt: hoursFromNow(-240),
      },
      {
        containerId: byCode.MSCU7784412.id,
        type: 'NAVIO_CHEGOU',
        title: 'Navio chegou ao terminal',
        description: 'MV Blue Estuary atracou e iniciou a operação.',
        location: 'Cais principal',
        occurredAt: hoursFromNow(-28),
      },
      {
        containerId: byCode.MSCU7784412.id,
        type: 'CONTAINER_DESCARREGADO',
        title: 'Unidade descarregada',
        description: 'Container enviado para segregação segura.',
        location: 'Patio alfandegado',
        occurredAt: hoursFromNow(-17),
      },
      {
        containerId: byCode.MSCU7784412.id,
        type: 'EM_FISCALIZACAO',
        title: 'Fiscalizacao em andamento',
        description: 'Conferencia de equipamentos sensiveis em andamento.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-12),
      },
      {
        containerId: byCode.MSCU7784412.id,
        type: 'LIBERADO',
        title: 'Carga liberada',
        description: 'Carga pronta para programação de coleta.',
        location: 'Receita Federal',
        occurredAt: hoursFromNow(-6),
      },
    ],
  });

  console.log(
    `Seed concluido com ${containers.length} containers, 4 navios e 4 transportadoras.`,
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
